name: CI

on:
  schedule: 
    - cron: "17 12 * * *"


jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo "Add other commands here"
          echo "This is a multi-line script"